import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Tabs from '../components/ui/Tabs';
import { tabPayload } from '../components/utils/TabUtils';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Tabs tabPayload={tabPayload} />
      </main>
    </div>
  );
}
